### ISSUE TITLE
Remove node_modules from the project

### ISSUE THREAD

**Issue by wetosc** [denddyprod/mini-card-game#1]
We must remove the node_modules folder from the repository, from .git history + add it to .gitignore.

Relevant examples:
https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

```bash
git filter-branch --tree-filter "rm -rf node_modules" --prune-empty HEAD
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
echo node_modules/ >> .gitignore
git add .gitignore
git commit -m 'Removing node_modules from git history'
git gc
git push origin master --force
```

**Comment by denddyprod** [comment]
It's a little bit strange, but I can't push after all changes. I got next error: 

_error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/denddyprod/mini-card-game.git'_

**Comment by denddyprod** [comment]
_**solved.**_

**Comment by denddyprod** [comment]
**_solved._**
